# Generated by Django 4.2 on 2025-09-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Stock',
            new_name='stock',
        ),
    ]
